### ISSUE TITLE
Example for New-VaporCondition error

### ISSUE THREAD

**Issue by pyrokin5** [SCRT-HQ/VaporShell#79]
Hello!
I believe this line:
https://github.com/SCRT-HQ/VaporShell/blob/d4f929246a6e1d98cbe2d9f9558590c163e3548e/VaporShell/Public/Primary%20Functions/New-VaporCondition.ps1#L40

Should look like this?
`$template.AddCondition(( `

**Comment by scrthq** [comment]
@pyrokin5 Good catch!!! Thank you for that! Getting that sorted asap :-)

**Comment by scrthq** [comment]
Updated and deployed, thanks again @pyrokin5 !
